### PR TITLE
feat: update specs and documentation

### PR DESCRIPTION
**Pull request by martinheidegger**
The new [test suite](https://github.com/dnslink-std/test) for DNSLink covers quite a few new topics.

_Note:_ The PR is set against the `next` branch. This is to prevent the immediate publication of the docs and allows us to publish the next version of DNSLink in one go as I will need to send a few more Pull Requests for updating other sections of the readme and links to the new libraries.

### CODE REVIEW

**Comment by lidel** [comment]
Apologies for delay on my end – I'll do my best to review it this week.

**Review by lidel — CHANGES_REQUESTED** [review]
Thank you @martinheidegger 
I reviewed and applied some feedback / changes  based on asks from https://github.com/dnslink-std/test/issues/ so it is easier for you to update

**Comment by lidel** [comment]
@martinheidegger sadly this got out of sync with changes to the `main` branch. 

I merged `next` into `main` and switched this PR to point at `main` – up to you if you want to resolve conflicts, or create a new PR based on the old feedback here.

**Comment by lidel** [comment]
@martinheidegger  lmk if/when this is ready for another review :pray:

**Comment by martinheidegger** [comment]
Yes, I am crunching on a deadline atm. I will update this issue within this
week.

**Comment by martinheidegger** [comment]
I went over the entire documentation once more. The current docs should contain all of your suggestions, are rebased to the current main but also are:

- Formatted to be 80~100 characters per line
- Use markdown reference links
- Use normalized language (records instead of mixed entries/records)

**Comment by ben221199** [comment]
Ah, this PR adds information about multiple DNSLinks and multiple DNSLinks in the same namespace. That is what I needed. Thanks.

**Review by lidel — APPROVED** [review]
Thank you @martinheidegger, I'm merging this so it does not slip between notification cracks again :see_no_evil: 

FYI I made some edits to reflect changes since 2021:
- go-ipfs got renamed to Kubo, ipfs.io websites moved to ipfs.tech
- Cloudflare and Fleek provide turn-key website hosting  solutions
- Gateway docs and resources got updated and changed links
- DNSLink is not limited to DWeb, adjusted language and added best
  practices around supporting multiple protocol records

Added some references:
- mentioned convention from RFC 1464 (<key>=<value>)
- due to this,  clarified that prefix is `dnslink=` and not `dnslink=/`
  and why value should start with `/namespace/` prefix

Fixed small typos and removed line numbers from code blocks.

**Pull request merged**
