### PR TITLE
Moving to vuepress.

### PR DESCRIPTION
**Pull request by martinheidegger**
This PR moves the site to be a simple vuepress documentation site.

This should make it easier to add interactive components to the site.

### CODE REVIEW

**Comment by martinheidegger** [comment]
The site seems to work: https://bafybeib22rxhavctqqmmjxhh5wsanw6w2vsdn5i7wp26hj6glbyxjzzgyy.on.fleek.co/
but the ci process is broken, probably related to #11

**Comment by martinheidegger** [comment]
Just noticed that the images didn't work, will fix soon.

**Comment by lidel** [comment]
@martinheidegger finished #11 – if you rebase this branch on top of latest `main` CI should become green :)

**Comment by martinheidegger** [comment]
Its green!

**Review by lidel — CHANGES_REQUESTED** [review]
Looks good!  Quick question before merge: 

- why are we using beta version of vue? do we know when it becomes stable? I'd like  to use some plugins  https://github.com/ipfs/ipfs-docs does, eg. https://github.com/IOriens/vuepress-plugin-canonical but  not sure if those will work with 2.x

**Comment by martinheidegger** [comment]
The beta version of vuepress 2 uses vue3. Long term an update from vuepress to vuepress2 would come anyways and I wanted to make less work for future people. vuepress2 has been in beta for a while now and [according to a discussion post](https://github.com/vuepress/vuepress-next/discussions/68#discussioncomment-782395) the API is pretty stable at this point. Seemed like a prudent approach, I can return back to regular vuepress if necessary.

**Comment by lidel** [comment]
Thanks!
Sounds sensible to stay: beta will turn stable this year, and it is already better than the old one.
Let's merge as-is, so it's easier to PR individual tweaks.

**Review by lidel — APPROVED** [review]

**Pull request merged**
